// @pageweaver/sdk — official TypeScript client for the PageWeaver PDF generation API.
// Server-side (Node 18+): uses the global `fetch` and `node:crypto` for webhook verification.

export { PageWeaver, type PageWeaverOptions } from "./client";
export type { FetchLike, RetryOptions } from "./http";

export {
  DocumentsResource,
  type WaitOptions,
  type DownloadOptions,
  type CreateSyncOptions,
} from "./documents";
export { TemplatesResource } from "./templates";
export { ProposalsResource } from "./proposals";
export { SchemasResource } from "./schemas";
export { UsageResource } from "./usage";
export { CommentsResource } from "./comments";
export { ReviewsResource } from "./reviews";
export { ShareLinksResource } from "./shareLinks";
export { EnvironmentsResource } from "./environments";
export { DeploymentsResource } from "./deployments";
export { FormsResource } from "./forms";
export { SubmissionsResource } from "./submissions";
export { ObjectTypesResource } from "./objectTypes";
export { ObjectsResource } from "./objects";
export { RelationshipTypesResource } from "./relationshipTypes";
export { SearchResource } from "./search";
export { WorkflowDefinitionsResource } from "./workflowDefinitions";
export { FormTemplatesResource } from "./formTemplates";
export { IntakeResource, IntakeSessionsResource } from "./intake";
export { ErrorCodesResource } from "./errorCodes";
export { EventsResource } from "./events";

export {
  PageWeaverError,
  PageWeaverApiError,
  PageWeaverAuthenticationError,
  PageWeaverPermissionError,
  PageWeaverNotFoundError,
  PageWeaverConflictError,
  PageWeaverValidationError,
  PageWeaverPlanRequiredError,
  PageWeaverRateLimitError,
  PageWeaverServerError,
  PageWeaverConnectionError,
  PageWeaverInvalidRequestError,
  PageWeaverTimeoutError,
  PageWeaverDocumentFailedError,
  type ApiErrorArgs,
} from "./errors";

export {
  verifyWebhook,
  verifyWebhookSignature,
  signWebhookBody,
  isDocumentEvent,
  isBatchEvent,
  PageWeaverWebhookSignatureError,
  WEBHOOK_SIGNATURE_HEADER,
  WEBHOOK_EVENT_HEADER,
  WEBHOOK_TIMESTAMP_HEADER,
  type VerifyWebhookOptions,
  type WebhookPayload,
  type DocumentWebhookPayload,
  type BatchWebhookPayload,
  type WebhookEventName,
  type DocumentWebhookEventName,
  type BatchWebhookEventName,
} from "./webhooks";

export type {
  DocumentStatus,
  DocumentOutput,
  PdfaLevel,
  RenderOptions,
  PageOptions,
  RenderingOptions,
  MetadataOptions,
  BandOptions,
  WatermarkOptions,
  StructureOptions,
  LocalizationOptions,
  SecurityOptions,
  PdfSecurityOptions,
  PdfPermissions,
  DownloadSecurityOptions,
  DeliveryOptions,
  EmailDeliveryOptions,
  CreateDocumentParams,
  CreateFromTemplateParams,
  CreateFromInlineParams,
  CreateDocumentResult,
  ValidateDocumentParams,
  ValidateDocumentResult,
  CreateSyncResult,
  DownloadInfo,
  Document,
  DocumentIntegrity,
  DocumentReviewSummary,
  DocumentVerification,
  DocumentAccessibility,
  AccessibilityViolation,
  DocumentListItem,
  ListDocumentsParams,
  DocumentPage,
  TemplateSummary,
  Template,
  TemplateVersionSummary,
  TemplateVersionSource,
  TemplateVersionDetail,
  VersionAttestation,
  // Provenance receipt (F02)
  ProvenanceReceipt,
  ReceiptIdentity,
  ReceiptSignature,
  // Document lineage: trust, diff, versions, representations
  DocumentTrustManifest,
  PayloadChange,
  DocumentDiffClassification,
  DocumentDiffResult,
  AppendDocumentVersionParams,
  AppendDocumentVersionResult,
  DocumentVersionInfo,
  DocumentVersionList,
  RepresentationInfo,
  RepresentationList,
  SchemaSummary,
  Schema,
  SchemaVersionSummary,
  SchemaVersionDetail,
  Usage,
  // Review layer
  AnchorType,
  ThreadStatus,
  CommentSeverity,
  CommentVisibility,
  MigrationStatus,
  Mention,
  CreateCommentParams,
  UpdateCommentParams,
  ReplyParams,
  CommentMessage,
  CommentThread,
  CommentThreadPage,
  ListCommentsParams,
  ReviewStatus,
  ParticipantRole,
  ParticipantStatus,
  ApprovalDecision,
  ReviewPolicy,
  ParticipantInput,
  CreateReviewParams,
  AddParticipantParams,
  ApprovalParams,
  ReviewParticipant,
  Approval,
  ReviewPolicyState,
  ReviewRequest,
  ReviewPage,
  ListReviewsParams,
  ShareLinkTargetType,
  ShareLinkPermissions,
  CreateShareLinkParams,
  ShareLink,
  CreatedShareLink,
  ShareLinkList,
  ListShareLinksParams,
  DocumentPageInfo,
  MigrateCommentsParams,
  MigrateCommentsResult,
  CommentMigrationRollup,
  // Template proposals (Pillar 2)
  ProposalStatus,
  ProposalCheckStatus,
  ProposalTextDiffStats,
  ProposalDatasetResult,
  ProposalDatasetCheck,
  ProposalArtifactDiff,
  ProposalCheckSummary,
  ProposalApproval,
  ProposalGate,
  TemplateProposal,
  OpenProposalParams,
  ListProposalsParams,
  ProposalPage,
  ProposalDecisionParams,
  PromoteProposalResult,
  // Environments & pins (Pillar 2)
  Environment,
  EnvironmentPin,
  CreateEnvironmentParams,
  UpdateEnvironmentParams,
  PromotePinsParams,
  PromotePinsResult,
  RollbackParams,
  RollbackResult,
  // Deployments (Pillar 3)
  DeploymentStatus,
  DeploymentSource,
  DeploymentAction,
  DeploymentResourceType,
  DeploymentChange,
  DeploymentWarning,
  DeploymentPlan,
  Deployment,
  DeploymentResource,
  DeploymentDetail,
  PlanDeploymentParams,
  ListDeploymentsParams,
  // Smart Forms (Phase D, V2-D06)
  SubmissionStatus,
  RuleMessage,
  EvaluatedState,
  RuleTraceEntry,
  RuleTrace,
  FormFieldContract,
  Form,
  FormDetail,
  FormSource,
  FormVersion,
  FormDataParams,
  ValidateFormResult,
  CreateSubmissionResult,
  Submission,
  // Generic cursor page
  CursorPage,
  CursorListParams,
  // Object types
  ObjectTypeStatus,
  ObjectTypeAccessPolicy,
  FieldPolicyOverlay,
  ObjectTypeView,
  ObjectTypeDetailView,
  ObjectTypeDraftParams,
  CreateObjectTypeParams,
  ObjectTypeVersionSummary,
  CompiledFieldPolicies,
  ObjectTypeVersionDetail,
  PublishObjectTypeParams,
  PublishedObjectTypeView,
  DeprecateObjectTypeParams,
  ListObjectTypesParams,
  // Objects
  BusinessObjectStatus,
  ObjectClassification,
  BusinessObjectView,
  BusinessObjectValueView,
  ListObjectsParams,
  CreateObjectParams,
  ReplaceObjectParams,
  BusinessObjectVersionSummary,
  ArchiveObjectParams,
  RelationshipCardinality,
  RelationshipTypeStatus,
  RelationshipTypeView,
  CreateRelationshipTypeParams,
  UpdateRelationshipTypeParams,
  DeprecateRelationshipTypeParams,
  ObjectRelationshipEdge,
  CreateRelationshipParams,
  RelationshipView,
  EndRelationshipParams,
  DocumentObjectLinkRole,
  DocumentObjectLinkView,
  LinkDocumentParams,
  UnlinkDocumentResult,
  // Search
  SearchSubjectType,
  SearchParams,
  SearchResultItem,
  SearchAccountPage,
  // Workflow definitions
  WorkflowDefinitionStatus,
  WorkflowDefinitionSpec,
  WorkflowDefinitionView,
  WorkflowDefinitionDetailView,
  WorkflowDefinitionVersionSummary,
  WorkflowDefinitionVersionDetail,
  ListWorkflowDefinitionsParams,
  // Fillable AcroForm templates
  UploadableFile,
  FormTemplateVersionSummary,
  FormTemplateSummary,
  JsonSchemaNode,
  FormTemplateDetail,
  CreateFormTemplateParams,
  FormTemplateUploadResult,
  FillFormTemplateParams,
  FillResultView,
  // Document intake / upload
  IntakeResultView,
  IntakeDocumentParams,
  UploadSessionStatus,
  UploadSessionView,
  CreateUploadSessionParams,
  BulkUploadFileParams,
  CreateUploadSessionBatchParams,
  CaptureBatchView,
  CreateUploadSessionBatchFileResult,
  CreateUploadSessionBatchResult,
  IntakeFinalizeResult,
  ArchiveMemberResultView,
  IntakeArchiveResultView,
  // Error registry
  ErrorCatalogEntry,
  ErrorCatalogResponse,
  // Domain events
  ListEventsParams,
  DomainEventView,
  DomainEventPage,
} from "./types";
